export class Prescription {
  prescriptionId: number = 0
  prescriptionNo: string = ''
  visitId: number = 0
  recordId: number = 0
  patientId: number = 0
  doctorId: number = 0
  totalAmount: number = 0
  feeStatus: string = ''
  auditStatus: string = ''
  status: string = ''
  diagnosis: string = ''
  usageNote: string = ''
  auditDoctorId: number = 0
  auditNote: string = ''
  auditedAt: string = ''
}
